services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - ./output:/opt/output/
    ports:
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  otel-app-one:
    build: otel-app-one/.
    ports:
      - 8080:8080
    environment:
      OTEL_SERVICE_NAME: "otel-app-one"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"


  otel-app-two:
    build: otel-app-two/.
    ports:
      - 8081:8081
    environment:
      OTEL_SERVICE_NAME: "otel-app-two"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"

