extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc: 
      http: 

processors:
  batch:

exporters:
  logging:
  kafka/traces:
    brokers:
      - kafka:9092
    encoding: otlp_json
    protocol_version: 3.6.0

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, kafka/traces]

  extensions: [health_check, pprof, zpages]